services:
  ai:
  
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    working_dir: /lab
    volumes:
      - ./:/lab
    ports:
      - "8811:8811"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]